#!/bin/sh
# publish-sample-repo.sh — publish your epkg repository to GitHub.
#
# Builds the sample packages (mkepkg), regenerates index.json with
# fresh sha256/size, then commits and pushes the repository layout to
# a GitHub repo. After that any machine (or your hobby OS) can use it:
#
#   epkg.conf:
#     mirror = https://raw.githubusercontent.com/<user>/<repo>/main
#
# usage:
#   scripts/publish-sample-repo.sh <git-url> [branch]
#   scripts/publish-sample-repo.sh --dry-run          # build only, no push
#
# The repository is published SIGNED: build-sample.sh generates (once)
# a demo Ed25519 key under sample/ and signs index.json into
# index.sig (signify format). Your users pin demo.pub via 'pubkey ='
# in epkg.conf; replace the demo key with your own offline key for a
# real repository (see FORMAT.md section 5).
#
# examples:
#   scripts/publish-sample-repo.sh git@github.com:myuser/my-epkg.git main
#   scripts/publish-sample-repo.sh https://github.com/myuser/my-epkg.git
#
# environment:
#   GITHUB_TOKEN   if set and the URL is https, the push embeds the
#                  token: https://x-access-token:<token>@github.com/...
#                  (recommended for CI; use a fine-grained token with
#                  "Contents: read & write" on the target repo)
#   PUBLISH_DIR    working clone directory (default: .publish-epkg-repo)
#
# The script is idempotent: re-running it updates the same repo.
# Alternative layout: you can also attach .epkg files to GitHub
# Releases and reference them via the "url" field in index.json.
set -e
cd "$(dirname "$0")/.."

DRY_RUN=0
if [ "${1:-}" = "--dry-run" ] || [ "${1:-}" = "-n" ]; then
    DRY_RUN=1
fi

URL=${1:-}
BRANCH=${2:-main}

if [ "$DRY_RUN" = 0 ] && [ -z "$URL" ]; then
    echo "usage: scripts/publish-sample-repo.sh <git-url> [branch]"
    echo "       scripts/publish-sample-repo.sh --dry-run"
    exit 1
fi

command -v git     >/dev/null || { echo "error: git not found";     exit 1; }
command -v python3 >/dev/null || { echo "error: python3 not found"; exit 1; }

# ---------- 1. build packages + index (mkepkg + sha256/size) ----------
echo "==> building packages (mkepkg)"
make mkepkg >/dev/null
sh tools/build-sample.sh

# ---------- 2. prepare the publishing clone ----------
if [ "$DRY_RUN" = 1 ]; then
    echo "==> dry run: repo is ready in sample-repo/"
    echo "    packages: $(ls sample-repo/packages/*.epkg | wc -l)"
    echo "    index entries: $(python3 -c 'import json;print(len(json.load(open("sample-repo/index.json"))["packages"]))')"
    echo "    epkg.conf line for your OS:"
    echo "      mirror = https://raw.githubusercontent.com/<user>/<repo>/<branch>"
    exit 0
fi

WORK=${PUBLISH_DIR:-.publish-epkg-repo}
if [ -d "$WORK/.git" ]; then
    echo "==> updating existing clone in $WORK"
    git -C "$WORK" fetch origin --prune
    git -C "$WORK" checkout -B "$BRANCH" "origin/$BRANCH" 2>/dev/null \
        || git -C "$WORK" checkout -B "$BRANCH"
else
    echo "==> initializing publishing repo in $WORK"
    rm -rf "$WORK"
    mkdir -p "$WORK"
    git -C "$WORK" init -b "$BRANCH" >/dev/null
    if [ -n "$URL" ]; then
        git -C "$WORK" remote add origin "$URL"
    fi
    # seed from an existing remote branch when there is one
    git -C "$WORK" fetch origin "$BRANCH" 2>/dev/null \
        && git -C "$WORK" checkout -B "$BRANCH" "FETCH_HEAD" 2>/dev/null || true
fi

mkdir -p "$WORK/packages"
cp sample-repo/packages/*.epkg "$WORK/packages/"
cp sample-repo/index.json "$WORK/index.json"
cp sample-repo/index.sig  "$WORK/index.sig"
cp sample-repo/demo.pub   "$WORK/demo.pub"

PUBKEY_LINE=$(tail -1 sample-repo/demo.pub)

# a short README helps people who land on the repo page
cat > "$WORK/README.md" <<EOF
# epkg repository

Generated by epkg-tools on $(date -u +%Y-%m-%dT%H:%M:%SZ).
Signed (Ed25519/signify); see demo.pub for the public key.

To use it, add to your \`epkg.conf\`:

    mirror = https://raw.githubusercontent.com/<user>/<repo>/$BRANCH
    pubkey = $PUBKEY_LINE

Then:

    epkg update
    epkg audit
    epkg install hello
EOF

# ---------- 3. commit + push ----------
git -C "$WORK" add -A
if git -C "$WORK" diff --cached --quiet; then
    echo "==> nothing changed, repository is up to date"
else
    git -C "$WORK" -c user.name="${GIT_AUTHOR_NAME:-epkg-publish}" \
        -c user.email="${GIT_AUTHOR_EMAIL:-epkg@localhost}" \
        commit -m "epkg repo update: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
fi

PUSH_URL="$URL"
if [ -n "${GITHUB_TOKEN:-}" ]; then
    case "$PUSH_URL" in
        https://github.com/*)
            PUSH_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${PUSH_URL#https://github.com/}"
            ;;
    esac
fi

echo "==> pushing to $URL (branch $BRANCH)"
git -C "$WORK" push "$PUSH_URL" "$BRANCH"

echo
echo "==> done. Add this to epkg.conf on every machine (and in your OS image):"
U=${URL#git@github.com:}
U=${U#https://github.com/}
U=${U%.git}
echo "    mirror = https://raw.githubusercontent.com/$U/$BRANCH"
echo "    pubkey = $PUBKEY_LINE"
echo "Then: epkg update && epkg audit && epkg install hello"
