/* epk_ed25519.c — Ed25519 (RFC 8032) for epkg-tools.
 *
 * Design notes
 * ------------
 * Field elements: 10 limbs of 26 bits each (radix 2^26), int64_t.
 * Overflow budget: |limb| < 2^27 at fe_mul input => products < 2^54,
 * each accumulator slot holds <= 10 products => < 2^58, safe in int64.
 * Reduction constants: a 10-limb wrap (2^260) is 608 mod p; the carry
 * out of slot 18 (2^494) is also 608 * 2^(26*9).
 *
 * Points: extended coordinates (X, Y, Z, T), a = -1 twisted Edwards.
 *   add:  add-2008-hwcd-3 (strongly unified, k = 2d)
 *   dbl:  dbl-2008-hwcd
 * Neither scalar multiplication nor comparison is constant time;
 * epkg uses Ed25519 for offline repo signing and index auditing,
 * not for online secret-auth protocols (README "Threat model").
 */
#include "epk_ed25519.h"
#include "epk_sha256.h"
#include "epk_libc.h"

typedef int64_t i64;

/* ---- constants (generated by scripts/gen_ed25519_consts.py) ---- */
static const i64 fe_P[10] = { 0x3ffffedLL, 0x3ffffffLL, 0x3ffffffLL, 0x3ffffffLL, 0x3ffffffLL, 0x3ffffffLL, 0x3ffffffLL, 0x3ffffffLL, 0x3ffffffLL, 0x1fffffLL };
static const i64 fe_D[10] = { 0x35978a3LL, 0x2d37284LL, 0x18ab75eLL, 0x1350507LL, 0x700aLL, 0x1de7a26LL, 0x740797LL, 0x3f9ce33LL, 0xee2b6fLL, 0x1480dbLL };
static const i64 fe_D2[10] = { 0x2b2f159LL, 0x1a6e509LL, 0x3156ebdLL, 0x26a0a0eLL, 0xe014LL, 0x3bcf44cLL, 0xe80f2eLL, 0x3f39c66LL, 0x1dc56dfLL, 0x901b6LL };
static const i64 fe_I[10] = { 0x20ea0b0LL, 0x386c9d2LL, 0x2478c4eLL, 0x1ab4bfLL, 0x32f4318LL, 0x37ef5e9LL, 0xd00993LL, 0x37c2cadLL, 0x804fc1LL, 0xae0c9LL };
static const i64 fe_BX[10] = { 0x325d51aLL, 0x18b5823LL, 0x27b2c95LL, 0x1825496LL, 0x692cc7LL, 0x375b717LL, 0x24e231fLL, 0x14ffb02LL, 0x2d3cd6eLL, 0x85a4dLL };
static const i64 fe_BY[10] = { 0x2666658LL, 0x1999999LL, 0x2666666LL, 0x1999999LL, 0x2666666LL, 0x1999999LL, 0x2666666LL, 0x1999999LL, 0x2666666LL, 0x199999LL };
static const i64 fe_BT[10] = { 0x1b7dda3LL, 0x3a2ace9LL, 0x12f56ddLL, 0x201dd45LL, 0x120f09fLL, 0x12af8dfLL, 0x2a4e8e6LL, 0x1d9959bLL, 0x30fd78bLL, 0x19e1d7LL };
static const uint8_t epk_L[32] = { 0xed,0xd3,0xf5,0x5c,0x1a,0x63,0x12,0x58,0xd6,0x9c,0xf7,0xa2,0xde,0xf9,0xde,0x14,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x10 };

#define MASK26 0x3ffffffLL

/* normalize limbs: t[0..8] -> [0, 2^26), t[9] -> [0, 2^27); preserves the
 * represented value (the limb-9 wrap adds c*608 == c*2^260, an exact value
 * correction). The final carry-only pass guarantees no limb-0 blowup. */
static void fe_reduce(i64 *t)
{
    i64 c;
    int pass, i;
    for (pass = 0; pass < 2; pass++) {
        for (i = 0; i < 9; i++) {
            c = t[i] >> 26;
            t[i] -= c << 26;
            t[i + 1] += c;
        }
        c = t[9] >> 26;
        t[9] -= c << 26;
        t[0] += c * 608;
    }
    /* carry pass without wrap: leaves t[0..8] < 2^26, t[9] < 2^27 */
    for (i = 0; i < 9; i++) {
        c = t[i] >> 26;
        t[i] -= c << 26;
        t[i + 1] += c;
    }
}

static void fe_add(i64 *h, const i64 *f, const i64 *g)
{
    i64 t[10];
    int i;
    for (i = 0; i < 10; i++) t[i] = f[i] + g[i];
    fe_reduce(t);
    memcpy(h, t, sizeof(t));
}

static void fe_sub(i64 *h, const i64 *f, const i64 *g)
{
    i64 t[10];
    int i;
    for (i = 0; i < 10; i++) t[i] = f[i] - g[i];
    fe_reduce(t);
    memcpy(h, t, sizeof(t));
}

static void fe_mul(i64 *h, const i64 *f, const i64 *g)
{
    i64 t[19];
    i64 c;
    int i, j;

    for (i = 0; i < 19; i++) t[i] = 0;
    for (i = 0; i < 10; i++)
        for (j = 0; j < 10; j++)
            t[i + j] += f[i] * g[j];

    /* pre-carry so slots 0..17 are < 2^26 */
    for (i = 0; i < 18; i++) {
        c = t[i] >> 26;
        t[i] -= c << 26;
        t[i + 1] += c;
    }
    /* carry out of slot 18: 2^494 == 608 * 2^234 (mod p) -> slot 9 */
    c = t[18] >> 26;
    t[18] -= c << 26;
    t[9] += c * 608;

    /* fold slots 10..18 into 0..8: a 10-limb shift is 2^260 == 608 */
    for (i = 10; i < 19; i++) {
        t[i - 10] += 608 * t[i];
        t[i] = 0;
    }
    fe_reduce(t);
    memcpy(h, t, sizeof(i64) * 10);
}

static void fe_sq(i64 *h, const i64 *f) { fe_mul(h, f, f); }

static void fe_copy(i64 *h, const i64 *f) { memcpy(h, f, sizeof(i64) * 10); }

static void fe_set1(i64 *h)
{
    memset(h, 0, sizeof(i64) * 10);
    h[0] = 1;
}

static void fe_set0(i64 *h) { memset(h, 0, sizeof(i64) * 10); }

/* a == b (mod p) — compare canonical encodings */
static void fe_tobytes(uint8_t out[32], const i64 *f);   /* forward */

static int fe_equal(const i64 *a, const i64 *b)
{
    uint8_t ba[32], bb[32];
    fe_tobytes(ba, a);
    fe_tobytes(bb, b);
    return memcmp(ba, bb, 32) == 0;
}

/* h = f^n, n = 256-bit little-endian exponent */
static void fe_pow(i64 *h, const i64 *f, const uint8_t e[32])
{
    i64 r[10];
    int i, j;
    fe_set1(r);
    for (i = 31; i >= 0; i--)
        for (j = 7; j >= 0; j--) {
            fe_sq(r, r);
            if ((e[i] >> j) & 1) fe_mul(r, r, f);
        }
    fe_copy(h, r);
}

/* p-2 (inverse exponent) */
static const uint8_t EXP_PM2[32] = {
    0xeb,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    0xff,0xff,0xff,0x7f
};
/* (p-5)/8 (square-root exponent, RFC 8032) */
static const uint8_t EXP_P58[32] = {
    0xfd,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,0xff,
    0xff,0xff,0xff,0x0f
};

static void fe_invert(i64 *h, const i64 *f)
{
    fe_pow(h, f, EXP_PM2);
}

/* canonical little-endian bytes (value taken mod p) */
static void fe_tobytes(uint8_t out[32], const i64 *f)
{
    i64 t[10];
    uint64_t acc = 0;
    int bits = 0, i, o, n;

    fe_copy(t, f);
    fe_reduce(t);
    /* full reduction mod p (t < 2^260 => at most ~31 subtractions,
     * in practice 0..2) */
    for (n = 0; n < 40; n++) {
        int ge = 1;
        for (i = 9; i >= 0; i--) {
            if (t[i] > fe_P[i]) { ge = 1; break; }
            if (t[i] < fe_P[i]) { ge = 0; break; }
        }
        if (!ge) break;
        fe_sub(t, t, fe_P);
    }
    /* assemble limbs (each < 2^26) into 32 bytes */
    for (i = 0; i < 32; i++) out[i] = 0;
    o = 0;
    for (i = 0; i < 10 && o < 32; i++) {
        acc |= (uint64_t)t[i] << bits;
        bits += 26;
        while (bits >= 8 && o < 32) {
            out[o++] = (uint8_t)(acc & 0xff);
            acc >>= 8;
            bits -= 8;
        }
    }
}

/* little-endian bytes -> fe (value taken mod p) */
static void fe_frombytes(i64 *h, const uint8_t b[32])
{
    i64 t[10];
    uint64_t acc = 0;
    int bits = 0, i, o;

    fe_set0(t);
    o = 0;
    for (i = 0; i < 32; i++) {
        acc |= (uint64_t)b[i] << bits;
        bits += 8;
        if (bits >= 26 && o < 10) {
            t[o++] = (i64)(acc & MASK26);
            acc >>= 26;
            bits -= 26;
        }
    }
    if (o < 10) t[o++] = (i64)(acc & MASK26);
    fe_reduce(t);
    memcpy(h, t, sizeof(t));
}

/* ---------------- group ops (extended coords) ---------------- */

typedef struct { i64 X[10], Y[10], Z[10], T[10]; } ge;

static void ge_zero(ge *r)          /* neutral element */
{
    fe_set0(r->X);
    fe_set1(r->Y);
    fe_set1(r->Z);
    fe_set0(r->T);
}

/* strongly unified add (add-2008-hwcd-3, k = 2d) */
static void ge_add(ge *r, const ge *p, const ge *q)
{
    i64 a[10], b[10], c[10], d[10], e[10], f[10], g[10], h[10];
    i64 t1[10], t2[10];

    fe_sub(t1, p->Y, p->X);  fe_sub(t2, q->Y, q->X);  fe_mul(a, t1, t2);
    fe_add(t1, p->Y, p->X);  fe_add(t2, q->Y, q->X);  fe_mul(b, t1, t2);
    fe_mul(c, p->T, q->T);   fe_mul(c, c, fe_D2);
    fe_mul(d, p->Z, q->Z);   fe_add(d, d, d);

    fe_sub(e, b, a);
    fe_sub(f, d, c);
    fe_add(g, d, c);
    fe_add(h, b, a);

    fe_mul(r->X, e, f);
    fe_mul(r->Y, g, h);
    fe_mul(r->Z, f, g);
    fe_mul(r->T, e, h);
}

/* doubling (dbl-2008-hwcd, a = -1) */
static void ge_dbl(ge *r, const ge *p)
{
    i64 a[10], b[10], c[10], d[10], e[10], f[10], g[10], h[10];
    i64 t[10], z[10];

    fe_sq(a, p->X);
    fe_sq(b, p->Y);
    fe_sq(c, p->Z);
    fe_add(c, c, c);
    fe_set0(z);
    fe_sub(d, z, a);            /* d = a*A = -A */

    fe_add(t, p->X, p->Y);
    fe_sq(t, t);
    fe_sub(t, t, a);
    fe_sub(e, t, b);            /* e = (x+y)^2 - A - B */

    fe_add(g, d, b);            /* g = b - a */
    fe_sub(f, g, c);            /* f = b - a - 2z^2 */
    fe_sub(h, d, b);            /* h = -a - b */

    fe_mul(r->X, e, f);
    fe_mul(r->Y, g, h);
    fe_mul(r->Z, f, g);
    fe_mul(r->T, e, h);
}

/* r = [s]p, s little-endian 32 bytes (MSB-first bit loop) */
static void ge_scalarmult(ge *r, const ge *p, const uint8_t s[32])
{
    ge acc, tmp;
    int i, j, bit;

    ge_zero(&acc);
    for (i = 31; i >= 0; i--)
        for (j = 7; j >= 0; j--) {
            ge_dbl(&tmp, &acc);
            acc = tmp;
            bit = (s[i] >> j) & 1;
            if (bit) {
                ge_add(&tmp, &acc, p);
                acc = tmp;
            }
        }
    *r = acc;
}

static void ge_scalarmult_base(ge *r, const uint8_t s[32])
{
    ge B;
    fe_copy(B.X, fe_BX);
    fe_copy(B.Y, fe_BY);
    fe_set1(B.Z);
    fe_copy(B.T, fe_BT);
    ge_scalarmult(r, &B, s);
}

static void ge_pack(uint8_t out[32], const ge *p)
{
    i64 zinv[10], x[10], y[10];
    uint8_t xb[32];

    fe_invert(zinv, p->Z);
    fe_mul(x, p->X, zinv);
    fe_mul(y, p->Y, zinv);
    fe_tobytes(out, y);
    fe_tobytes(xb, x);
    out[31] = (uint8_t)(out[31] | ((xb[0] & 1) << 7));
}

/* decode a point; -1 on failure */
static int ge_unpack(ge *r, const uint8_t in[32])
{
    i64 y[10], u[10], v[10], x[10], t[10], one[10], neg[10];
    uint8_t yb[32];
    int sign = (in[31] >> 7) & 1;

    memcpy(yb, in, 32);
    yb[31] = (uint8_t)(yb[31] & 0x7f);
    fe_frombytes(y, yb);

    fe_set1(one);
    fe_sq(t, y);
    fe_sub(u, t, one);              /* u = y^2 - 1 */
    fe_mul(v, t, fe_D);
    fe_add(v, v, one);              /* v = d*y^2 + 1 */

    /* x = u*v^3 * (u*v^7)^((p-5)/8) */
    {
        i64 v3[10], v7[10], uv7[10], powr[10], chk[10];
        fe_sq(v3, v);
        fe_mul(v3, v3, v);          /* v^3 */
        fe_mul(v7, v3, v3);
        fe_mul(v7, v7, v);          /* v^7 */
        fe_mul(uv7, u, v7);
        fe_pow(powr, uv7, EXP_P58);
        fe_mul(x, u, v3);
        fe_mul(x, x, powr);

        fe_sq(chk, x);
        fe_mul(chk, chk, v);        /* chk = v*x^2 */
        if (fe_equal(chk, u)) {
            /* ok */
        } else {
            fe_set0(neg);
            fe_sub(neg, neg, u);    /* neg = -u */
            if (!fe_equal(chk, neg)) return -1;
            fe_mul(x, x, fe_I);     /* x *= sqrt(-1) */
        }
    }

    /* pick the branch matching the sign bit */
    {
        uint8_t xb[32];
        fe_tobytes(xb, x);
        if ((int)(xb[0] & 1) != sign) {
            i64 z[10];
            fe_set0(z);
            fe_sub(x, z, x);
        }
    }
    fe_copy(r->X, x);
    fe_copy(r->Y, y);
    fe_set1(r->Z);
    fe_mul(r->T, x, y);
    return 0;
}

/* ---------------- scalar arithmetic mod L ---------------- */

/* 1 if a >= b (little-endian, len bytes) */
static int bn_ge(const uint8_t *a, const uint8_t *b, int len)
{
    int i;
    for (i = len - 1; i >= 0; i--) {
        if (a[i] > b[i]) return 1;
        if (a[i] < b[i]) return 0;
    }
    return 1;   /* equal */
}

static void bn_sub(uint8_t *a, const uint8_t *b, int len)   /* a -= b */
{
    int i, borrow = 0;
    for (i = 0; i < len; i++) {
        int v = (int)a[i] - (int)b[i] - borrow;
        if (v < 0) { v += 256; borrow = 1; } else borrow = 0;
        a[i] = (uint8_t)v;
    }
}

/* reduce a 64-byte little-endian value mod L -> out[32] */
static void modL(uint8_t out[32], const uint8_t in[64])
{
    uint8_t rem[33];
    int bit, i;

    memset(rem, 0, sizeof(rem));
    for (bit = 511; bit >= 0; bit--) {
        unsigned carry = (unsigned)((in[bit >> 3] >> (bit & 7)) & 1);
        for (i = 0; i <= 32; i++) {
            unsigned v = ((unsigned)rem[i] << 1) | carry;
            rem[i] = (uint8_t)(v & 0xff);
            carry = v >> 8;
        }
        if (bn_ge(rem, epk_L, 32))
            bn_sub(rem, epk_L, 32);
    }
    memcpy(out, rem, 32);
}

/* out = (a*b) mod L  (a, b < L, 32 bytes LE) */
static void mul_modL(uint8_t out[32], const uint8_t a[32], const uint8_t b[32])
{
    uint16_t t[64];
    uint8_t prod[64];
    int i, j, k;

    memset(t, 0, sizeof(t));
    for (i = 0; i < 32; i++) {
        unsigned long long ai = a[i], carry = 0;
        if (!ai) continue;
        for (j = 0; j < 32; j++) {
            unsigned long long v = (unsigned long long)t[i + j] +
                                   ai * (unsigned long long)b[j] + carry;
            t[i + j] = (uint16_t)(v & 0xff);
            carry = v >> 8;
        }
        for (k = i + 32; carry && k < 64; k++) {
            unsigned long long v = (unsigned long long)t[k] + carry;
            t[k] = (uint16_t)(v & 0xff);
            carry = v >> 8;
        }
    }
    for (i = 0; i < 64; i++) prod[i] = (uint8_t)t[i];
    modL(out, prod);
}

/* out = a + b mod L (a, b < L) */
static void add_modL(uint8_t out[32], const uint8_t a[32], const uint8_t b[32])
{
    uint8_t s[32];
    int i, carry = 0;
    for (i = 0; i < 32; i++) {
        int v = (int)a[i] + (int)b[i] + carry;
        s[i] = (uint8_t)(v & 0xff);
        carry = v >> 8;
    }
    (void)carry;                    /* sum < 2L, cannot carry out */
    if (bn_ge(s, epk_L, 32))
        bn_sub(s, epk_L, 32);
    memcpy(out, s, 32);
}

/* ---------------- public API ---------------- */

static void clamp_scalar(uint8_t a[32], const uint8_t hash[64])
{
    memcpy(a, hash, 32);
    a[0]  &= 248;
    a[31] &= 63;
    a[31] |= 64;
}

void epk_ed25519_pubkey(const uint8_t seed[32], uint8_t pub[32])
{
    epk_sha512 h;
    uint8_t hash[64], a[32];
    ge A;

    epk_sha512_init(&h);
    epk_sha512_update(&h, seed, 32);
    epk_sha512_final(&h, hash);
    clamp_scalar(a, hash);
    ge_scalarmult_base(&A, a);
    ge_pack(pub, &A);
}

void epk_ed25519_sign(const uint8_t seed[32],
                      const void *msg, size_t msglen,
                      uint8_t sig[64])
{
    epk_sha512 h;
    uint8_t hash[64], a[32], prefix[32], pub[32];
    uint8_t r32[32], k32[32], ared[32], s32[32], a64[64], sum[32];
    ge R;

    epk_sha512_init(&h);
    epk_sha512_update(&h, seed, 32);
    epk_sha512_final(&h, hash);
    clamp_scalar(a, hash);
    memcpy(prefix, hash + 32, 32);

    epk_ed25519_pubkey(seed, pub);

    /* r = H(prefix || M) mod L */
    epk_sha512_init(&h);
    epk_sha512_update(&h, prefix, 32);
    epk_sha512_update(&h, msg, msglen);
    epk_sha512_final(&h, hash);
    modL(r32, hash);

    ge_scalarmult_base(&R, r32);
    ge_pack(sig, &R);                       /* first half = R */

    /* k = H(R || A || M) mod L */
    epk_sha512_init(&h);
    epk_sha512_update(&h, sig, 32);
    epk_sha512_update(&h, pub, 32);
    epk_sha512_update(&h, msg, msglen);
    epk_sha512_final(&h, hash);
    modL(k32, hash);

    /* S = (r + k*a) mod L */
    memset(a64, 0, sizeof(a64));
    memcpy(a64, a, 32);
    modL(ared, a64);
    mul_modL(s32, k32, ared);
    add_modL(sum, r32, s32);
    memcpy(sig + 32, sum, 32);
}

int epk_ed25519_verify(const uint8_t pub[32],
                       const void *msg, size_t msglen,
                       const uint8_t sig[64])
{
    epk_sha512 h;
    uint8_t hash[64], k32[32];
    ge A, R, P1, P2, T;
    uint8_t b1[32], b2[32];

    /* S must be strictly below L (canonicity) */
    if (bn_ge(sig + 32, epk_L, 32)) return -1;

    if (ge_unpack(&A, pub) != 0) return -1;
    if (ge_unpack(&R, sig) != 0) return -1;

    epk_sha512_init(&h);
    epk_sha512_update(&h, sig, 32);         /* R bytes */
    epk_sha512_update(&h, pub, 32);
    epk_sha512_update(&h, msg, msglen);
    epk_sha512_final(&h, hash);
    modL(k32, hash);

    ge_scalarmult_base(&P1, sig + 32);      /* [S]B */
    ge_scalarmult(&T, &A, k32);             /* [h]A */
    ge_add(&P2, &R, &T);                    /* R + [h]A */

    ge_pack(b1, &P1);
    ge_pack(b2, &P2);
    return memcmp(b1, b2, 32) == 0 ? 0 : -1;
}
